name: poof_worker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_flavor: ^3.1.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  collection: ^1.19.0
  fl_chart: ^1.0.0
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  go_router: ^16.0.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  json_path: ^0.7.2
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  path_provider_android: ^2.2.10
  path_provider_foundation: ^2.4.0
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  shared_preferences: ^2.3.2
  shared_preferences_android: ^2.3.2
  shared_preferences_foundation: ^2.5.2
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  shared_preferences_windows: ^2.4.1
  sqflite: ^2.3.3+1
  sqflite_common: ^2.5.4+3
  timeago: ^3.6.1
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.10
  url_launcher_ios: ^6.3.1
  url_launcher_linux: ^3.2.0
  url_launcher_macos: ^3.2.1
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.3
  url_launcher_windows: ^3.1.2
  app_links: ^6.4.0
  logger: ^2.5.0
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.0
  country_flags: ^3.0.0
  poof_flutter_auth:
    git:
      url: git@github.com:poofware/flutter-auth.git
      ref: main
  poof_flutter_widgets:
    git:
      url: git@github.com:poofware/flutter-widgets.git
      ref: main
  http: ^1.3.0
  uuid: ^4.5.1
  google_maps_flutter: ^2.12.2
  google_maps_flutter_android: ^2.16.1
  google_maps_flutter_platform_interface: ^2.12.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  video_player: ^2.9.5 
  visibility_detector: ^0.4.0+2
  animations: ^2.0.11
  image_picker: ^1.1.2
  path: ^1.9.1
  world_flags: ^2.3.0
  android_intent_plus: ^5.3.0
  flutter_google_places_sdk: ^0.4.2+1
  flutter_typeahead: ^5.2.0
  haptic_feedback: ^0.5.1+1

dependency_overrides:
  poof_flutter_auth:
    path: ../../shared/flutter-auth
  poof_flutter_widgets:
    path: ../../shared/flutter-widgets

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  image: ^4.2.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  otp: ^3.1.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path: 'assets/images/app_icon.png'
  adaptive_icon_foreground: "assets/images/app_icon_fg_android.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"                # light background
  color_dark: "#000000"           # dark-mode background
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"
    color: "#FFFFFF"
    color_dark: "#000000"

flutter:

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/images/
    - assets/vectors/
