x-build-network: &build-network
  network: host

services:
  # ----------------------
  # 1) Postgres DB
  # ----------------------
  db:
    image: postgres:13
    container_name: ${COMPOSE_DB_NAME?Docker Compose Config Error! COMPOSE_DB_NAME is not set!}_instance
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "0:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      db_network:
        aliases:
          - ${COMPOSE_DB_NAME?Docker Compose Config Error! COMPOSE_DB_NAME is not set!}
    profiles:
      - unassigned

  # ----------------------
  # 2) Database Migration Service
  # ----------------------
  migrate:
    build:
      context: .
      dockerfile: devops-toolkit/backend/docker/migrate.Dockerfile
      <<: *build-network
      args:
        ENV: ${ENV?Docker Compose Config Error! ENV is not set!}
        HCP_ORG_ID: ${HCP_ORG_ID?Docker Compose Config Error! HCP_ORG_ID is not set!}
        HCP_PROJECT_ID: ${HCP_PROJECT_ID?Docker Compose Config Error! HCP_PROJECT_ID is not set!}
        HCP_ENCRYPTED_API_TOKEN: ${HCP_ENCRYPTED_API_TOKEN?Docker Compose Config Error! HCP_ENCRYPTED_API_TOKEN is not set!}
        HCP_APP_NAME_FOR_DB_SECRETS: ${HCP_APP_NAME_FOR_DB_SECRETS?Docker Compose Config Error! HCP_APP_NAME_FOR_DB_SECRETS is not set!}
        MIGRATIONS_PATH: ${MIGRATIONS_PATH?Docker Compose Config Error! MIGRATIONS_PATH is not set!}
        UNIQUE_RUN_NUMBER: ${UNIQUE_RUN_NUMBER?Docker Compose Config Error! UNIQUE_RUN_NUMBER is not set!}
        UNIQUE_RUNNER_ID: ${UNIQUE_RUNNER_ID?Docker Compose Config Error! UNIQUE_RUNNER_ID is not set!}
    image: ${COMPOSE_PROJECT_NAME?Docker Compose Config Error! COMPOSE_PROJECT_NAME is not set!}-migrate
    pull_policy: build
    container_name: ${COMPOSE_PROJECT_NAME?Docker Compose Config Error! COMPOSE_PROJECT_NAME is not set!}-migrate_instance
    profiles:
      - unassigned
    networks:
      - db_network
    environment:
      HCP_TOKEN_ENC_KEY: ${HCP_TOKEN_ENC_KEY?Docker Compose Config Error! HCP_TOKEN_ENC_KEY is not set!}
      MIGRATE_MODE: ${MIGRATE_MODE:-forward}

volumes:
  db_data:
    name: ${COMPOSE_DB_NAME?Docker Compose Config Error! COMPOSE_DB_NAME is not set!}_data

networks:
  db_network:
    external: true
    name: ${COMPOSE_NETWORK_NAME?Docker Compose Config Error! COMPOSE_NETWORK_NAME is not set!}
