name: poof_flutter_auth
description: Common auth package for Poof applications (Worker, PM, etc.)
version: 0.0.1
publish_to: none  # Private package

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.poof.flutterauth
        pluginClass: StandardIntegrityPlugin

dependencies:
  http: ^1.3.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_udid: ^4.0.0
  app_device_integrity: ^1.1.0
  uuid: ^4.5.1
  device_check: ^1.0.0
  cbor: ^6.3.7
  device_info_plus: ^11.5.0
  synchronized: ^3.4.0

